### ISSUE TITLE
Bug in inventory_grid_stacked_ex_transfer.tscn Item Missing When Merging

### ISSUE THREAD

**Issue by hellowin** [peter-kish/gloot#102]
I found a bug in the inventory_grid_stacked_ex_transfer.tscn
1. When I merge the same item type (1x1 to 1x1 or 2x2 to 2x2), it works fine
2. When I merge item 1x1 to 2x2 it works fine, which is it's rejected, as expected
3. But when I merge item 2x2 to 1x1, the item went missing

![Screenshot 2023-06-22 200634](https://github.com/peter-kish/gloot/assets/1904744/ab88622b-81d4-4d59-9ade-145d63a2b4de)

**Comment by peter-kish** [comment]
Thanks for pointing this out!
Should be fixed in ef176f2e5f255e53723442ef344d942169ece4fa.
