### ISSUE TITLE
Godot 4.1 editor plugin signature changed

### ISSUE THREAD

**Issue by ICEFIR** [peter-kish/gloot#103]
**Situation**
when i upgraded godot to 4.1 the language server prompts I've encountered this error
```
res://addons/gloot/editor/inventory_inspector_plugin.gd:47 - Parse Error: The function signature doesn't match the parent. Parent signature is "_parse_property(Object, Variant.Type, String, PropertyHint, String, int, bool) -> bool".
```
Upon checking, its related to upstream issue https://github.com/godotengine/godot/issues/75311, where a code gen fix has resulted in changed function signature

**Expected Behavior**
Editor plugin to match the expected parent signature

i can raise a PR if you want, given its just 1 LOC :)

**Comment by peter-kish** [comment]
Should be fixed in 30fc597d22cde0139a227a2254b4bb562fed35fc.
Thanks for the input!
