### ISSUE TITLE
Selecting prototype id causing crash.

### ISSUE THREAD

**Issue by LeeWannacott** [peter-kish/gloot#108]
![Screenshot from 2023-08-08 01-17-44](https://github.com/peter-kish/gloot/assets/49783296/71351e3f-85b8-405f-b2e7-2dd6fb67da43)

Selecting prototype id using the item_prototype_id_editor is causing a crash.

![image](https://github.com/peter-kish/gloot/assets/49783296/321e12d1-d1d8-4922-9ffa-c6809f28f2a7)

Line 87:
![image](https://github.com/peter-kish/gloot/assets/49783296/3a18fa8b-b1bf-4b92-af7d-bba7b6360cca)

It's like its having issues closing a window that doesn't exist??? Maybe its a race condition :shrug: 

This may have been fixed in the new version?, but, alas I can't get it working as per other issue :sweat_smile: https://github.com/peter-kish/gloot/issues/107

**Comment by peter-kish** [comment]
I took a quick look and managed to reproduce it. Seems to be caused by b72dcf31ac20f11cb83af7619c2b4caabb545ad5. Working on it...

**Comment by peter-kish** [comment]
32cd1473a25296da5fc6ca95e80f184928b17cdc should address this, but it's only a quick fix until the inspector plugin code goes through some serious rework.
