### ISSUE TITLE
Feature Request: method to select items.

### ISSUE THREAD

**Issue by LeeWannacott** [peter-kish/gloot#110]
![image](https://github.com/peter-kish/gloot/assets/49783296/08ba5cf0-63d7-4906-b1aa-1f30f705adb2)

```
if Input.is_action_just_pressed("inventory_slot1"):
var hotbar_slot = $"../UI/HotbarAndBackpack/InventoryHotbar".get_item_at(Vector2i(0,0))
		if hotbar_slot != null:
			print(hotbar_slot.get_title())
```
I can press the key (1) on my keyboard to get the title/id of the item in hotbar slot 1, but it doesn't look like there is a method in the docs for programmatically selecting an item (like when you left click with the mouse).

It kind of relates to this https://github.com/peter-kish/gloot/pull/67 . However, I don't really need full blown keyboard or controller support. Just a method where you can select an item would be great (mainly just the visual of it highlighted, I can program the player logic that it is selected), I think it would be a pretty common use case as well.

**Comment by peter-kish** [comment]
Yeah, I think having a `select_inventory_item(item: InventoryItem)` for all `CtrlInventory*` classes would make a lot of sense and it wouldn't be too hard to implement. Especially since there's already a `get_selected_inventory_items()` method (could also make it `select_inventory_items(items: Array)`).

**Comment by peter-kish** [comment]
[CtrlInventory](https://github.com/peter-kish/gloot/blob/master/docs/ctrl_inventory.md) and [CtrlInventoryGrid](https://github.com/peter-kish/gloot/blob/master/docs/ctrl_inventory_grid.md) now have a `select_inventory_item(item: InventoryItem)` method that selects the given item in the inventory.
`deselect_inventory_item()` can be used to deselect the currently selected item.
`get_selected_inventory_items()` has been replaced with `get_selected_inventory_item()`, as multi-selections are not yet supported.
