### ISSUE TITLE
Error message when no selected styles on CtrlInventoryGridEx

### ISSUE THREAD

**Issue by LeeWannacott** [peter-kish/gloot#115]
If you don't have any selected styles.
![image](https://github.com/peter-kish/gloot/assets/49783296/002ae3ad-cd45-4090-b66c-4bdd83a028e6)

Pretty minor bug/issue really that doesn't effect anything other than clogging up the debugger with Error messages. Its easy to fix because you just select styles :brain: .

You are probably already aware of this; thought I would report it anyway : /

**Comment by peter-kish** [comment]
I actually wasn't aware of it at all :worried:. Thanks for the input!
Should be fixed in c2c233519af31e28de419effa992f81c663faf94 on the [dev_v2_3_3](https://github.com/peter-kish/gloot/tree/dev_v2_3_3) branch.
Will close the issue once it gets merged to master.

**Comment by peter-kish** [comment]
Changes have been merged to master
