### ISSUE TITLE
Increasing lag/slow down when using create_and_add_item with InventoryGridStacked

### ISSUE THREAD

**Issue by randomnewb** [peter-kish/gloot#117]
Hi there,

First off, amazing plugin, thank you very much for your hard work on this.

I recently started using the Stacked Grid system rather than the list inventory and noticed that with every added item (via create_and_add_item), the game gets additively slower (I am using the Profiler in the Debugger, and there is an increasingly larger and larger lag spike per item added). I didn't note any other bugs in the Debugger. 

The only thing other thing I have done is changed the Item Protoset to have item width/heights/stack sizes. I've also added some "Styles" to the CtrlInventoryGridEx which I took from the examples.

Could it be possible that the way I am adding the item is causing the lag? It must be, right? I create an actual Node with an Area2D that moves toward the player, and upon collision calls the create_and_add_item, passing in the prototype_id and then removing the Node from the main world. This did not cause any lag when using the previous Inventory system (the basic list).

Thank you in advance for your support on this!

P.S. I am using an older version of the plugin, 2.3.1. I am having a lot of trouble updating to 2.3.4, but maybe that will fix it as well.

**Comment by peter-kish** [comment]
Hey, thanks for the kind words!

Honestly, I don't think you're doing anything wrong that causes the lag because it's not the first time I'm having performance issues with the grid system. I did quite a lot of refactoring lately and some of those bugs might have been resurrected..

I'll take a look at it, probably in the following week or two, but I already have an idea what could be causing the problem.

**Comment by peter-kish** [comment]
Just to confirm that I managed to reproduce the problem and it seems to be caused by my poorly optimized code (the `get_space_for` function defined in `grid_constraint.gd` seems to have exponential complexity). 

Hopefully I will come up with some optimizations...

**Comment by peter-kish** [comment]
`Inventory.create_and_add_item()` performance has been improved in [v2.3.5](https://github.com/peter-kish/gloot/releases/tag/v2.3.5).
