### ISSUE TITLE
bad performance with big grid inventories

### ISSUE THREAD

**Issue by RedNukem** [peter-kish/gloot#125]
Hello there, 
First things first, thank you very much for an awesome plugin it's one of the main reasons i switched to Godot.

I'm making a game where the player will have a "big Stash" to keep things between "runs" (no time to explain now) the thing is, as the title says, every time I move an item from an inventory to another (using UI "CtrlInventoryGridEx" nodes) or adding them in the editor the whole thing stops for a few seconds.

To reproduce: 
Simply generate a 10x40 grid inventory, configure any protoset (with 1 item of 1x1 size) and add the item from the editor
if the lag is not big enough to feel it then use 10x100 (my original intended size)

I was trying to figure out the problem on my own using some breakpoints and the UI nodes, I think I found the reason but i'm not sure how to fix it.
In "grid_constraint.gd" i saw that the function called "transfer_to" witch checks if there's space for it with "destination.rect_free(rect)" but then proceeds to add the item without positional info and then move it in place, seems less than ideal for the specific inventory (grid) but fine in general.
Then I noticed that there's a function that will seek in the entirety of the grid called "find_free_space" at line 337, and it's called too many times for every transfer/addage of items, with a comment just above it stating: 
"# TODO: Check if find_free_place is needed"
Something tells me it's not needed that many times.

Anyway, thank you for everything and i hope i can help figuring this one out.

PS: using Godot v4.1.3 mono and the latest Gloot v2.3.6

**Comment by peter-kish** [comment]
Hey, thanks for the input!

Yeah, `InventoryGrid` performance tends to fall when using large grid sizes and it's not the first time it needs fixing... Anyways, I did some additional optimizations in [v2.3.7](https://github.com/peter-kish/gloot/releases/tag/v2.3.7), especially for items that are 1x1 in size. It's still not perfect, but it should improve performance significantly for general usage.

Let me know if the issue is still present after the upgrade.

**Comment by RedNukem** [comment]
Hi there, wow, just tested a big grid of 10x100 with 1x1 items and 4x4 items just in case and it's fast, so you pretty much nailed it!
Awesome work, thanks to you, size truly does not matter anymore 😉  
grid size that is.

Thanks again!
