### ISSUE TITLE
DragItem display level

### ISSUE THREAD

**Issue by ah-ne** [peter-kish/gloot#159]
I use a CanvasLayer to hold and display the inventory (CtrlInventoryGridEx/InvetoryGridStacked). The drag sprite ist always behind the CanvasLayer the option drag_sprite_z_index has no impact. 

Offtopic: Really coll project. For me so far the best invetory system for godot.

**Comment by peter-kish** [comment]
This is probably because gloot is using its own drag&drop system instead of Godot's, because Godot's is not very customizable. It's not the first time that rendering the drag preview causes problems :(

P.S. Thanks!

**Comment by peter-kish** [comment]
Should be fixed in [v2.4.2](https://github.com/peter-kish/gloot/releases/tag/v2.4.2)
