### ISSUE TITLE
DrapItem position

### ISSUE THREAD

**Issue by ah-ne** [peter-kish/gloot#160]
The position of the drag item use the global_mouse_position for displaying and not the local_mouse_position. In some cases this is correct but in others not. In my situation the item is displayed far off the mous position. A option would be nice. Maybe always use local_mouse_postion is alway correct? I am not sure.

**Comment by ah-ne** [comment]
Yes it is the same project as 159. I have a world map and if I "scroll/move" around it the wrong offset of the drag item getting bigger. I thought about it again. And it is maybe vise versa. It takes the local mouse position as global position.   

thx for replying so fast.

**Comment by peter-kish** [comment]
Should be fixed in [v2.4.2](https://github.com/peter-kish/gloot/releases/tag/v2.4.2)
