### ISSUE TITLE
on 2.4.1 images not resize

### ISSUE THREAD

**Issue by juliusspeak** [peter-kish/gloot#161]
After switching to version 2.4.1, images no longer fit the cell size
![1](https://github.com/peter-kish/gloot/assets/35423496/05ae35a2-e563-478e-aca1-75414576ddbe)
![2](https://github.com/peter-kish/gloot/assets/35423496/9cbc35b3-c7ce-4673-87cb-983d1f5c972a)

**Comment by peter-kish** [comment]
Should be fixed in [v2.4.2](https://github.com/peter-kish/gloot/releases/tag/v2.4.2)
