### ISSUE TITLE
Dragging item from ItemSlot off centre. v2.4.3

### ISSUE THREAD

**Issue by LeeWannacott** [peter-kish/gloot#167]
Hey just updated to 2.4.3; nice work on the icon resizing options!

I found a ~~couple~~ thruple of bugs. 

1. When dragging an item from the ItemSlot the image is off centre (probably same issue as this but for item slot rather than inventory grid:  (https://github.com/peter-kish/gloot/issues/160) 

2.  The actual item slots default item icon seems to be draggable.

3. The size of the item dragged from the item slot is not the same as when dragged from the inventory grid (its way bigger.)

Video:

https://github.com/peter-kish/gloot/assets/49783296/c0e4880e-e354-47bb-9d23-426657978317

P.S

~~4. Also dropping your item on-top off the ItemSlot makes the default icon dissapear, whereas I think it should probably draw on-top of it.~~ Nevermind using a StyleBoxTexture in Slot style solves this.

**Comment by LeeWannacott** [comment]
I also found this bug where your item just vanishes. Not sure what causes it. Seems like it happens dragging and dropping into the same slot that is equipped; when dragging and dropping onto the corner of the item slot. Its pretty easy to make it happen.



https://github.com/peter-kish/gloot/assets/49783296/02c456a7-8ad2-4019-a75a-46726422c8e5

**Comment by peter-kish** [comment]
Seems like the `CtrlItemSlot` icon scaling options introduced quite a few bugs 😬 I'll make them a priority for the next release.

**Comment by peter-kish** [comment]
I'm afraid I'll need some more information on most of these issues... Apart  from the 2nd one (dragable default icon), I wasn't really able to reproduce them. Here's the minimal project I was playing around with:

[item_slot_bug_test.zip](https://github.com/peter-kish/gloot/files/14409730/item_slot_bug_test.zip)

**Comment by LeeWannacott** [comment]
@peter-kish 

[item_slot_bug_test.zip](https://github.com/peter-kish/gloot/files/14420429/item_slot_bug_test.zip)

I reproduced number 1; it is to do with the scale of the control being less than 1.

Number 3 is present in your example/minimal project; when dragging your item from slot to slot, or back to the inventory grid I think the size of the item should be what is set (width and height) in the protoset (.i.e the same as when dragging item from the inventory grid).

Not sure about the vanishing inventory. I need to look into it more when have time.

**Comment by LeeWannacott** [comment]
@peter-kish 

[vanishing_inventory_reproduced.zip](https://github.com/peter-kish/gloot/files/14420937/vanishing_inventory_reproduced.zip)

Okay figured out the case of the vanishing inventory you just need to swap between inventory slots and then drop the item onto the current CtrlItemSlot you switched to:

https://github.com/peter-kish/gloot/assets/49783296/89fe576d-8520-4446-a59c-3d5687fd3624

I don't think this is related to the other bugs.

**Comment by peter-kish** [comment]
I think there are several unrelated problems addressed here, so I created separate issues for each of them to make discussions easier:

https://github.com/peter-kish/gloot/issues/174
https://github.com/peter-kish/gloot/issues/175
https://github.com/peter-kish/gloot/issues/176
https://github.com/peter-kish/gloot/issues/177

@LeeWannacott Can you take a quick look if anything is missing? After that I'll close this one.

**Comment by LeeWannacott** [comment]
@peter-kish Yeah fair enough, Looks good to me!
