### ISSUE TITLE
Break inventory after pause game

### ISSUE THREAD

**Issue by juliusspeak** [peter-kish/gloot#181]
![img](https://github.com/peter-kish/gloot/assets/35423496/29a49fa7-3c2b-4a98-9afc-d3a4df5ef7a1)

**Comment by peter-kish** [comment]
😬

**Comment by peter-kish** [comment]
I didn't manage to reproduce this:
![Peek 2024-03-02 15-42](https://github.com/peter-kish/gloot/assets/11254996/cfee3731-80b4-4fc7-9748-254b71ea5125)

I suggest one of the following:
* Try v2.4.4. Some of the fixes included in that version might fix this one as well.
* Try creating a [minimal reproducible example](https://en.m.wikipedia.org/wiki/Minimal_reproducible_example). That way I can try to debug the problem.

**Comment by peter-kish** [comment]
Closed due to staleness
