### ISSUE TITLE
Item_Dropped signal missing from Ctrl_inventory_grid in current version

### ISSUE THREAD

**Issue by Karbonicc** [peter-kish/gloot#183]
As stated above, the Item_Dropped Signal is no longer activated when dragging an item outside of the inventory. The signal still exists, but doesn't seem to be mentioned in the Ctrl_Inventory_Grid script anymore.  This means any code or function related to this signal now no longer works. 

Is there a new way to restore functionality to this? Was it moved, or is it simply missing?

**Comment by peter-kish** [comment]
Looks like it has been removed during some code restructuring in the past. It should be fixed now in a9eaee7c982ec171782e81c963791c64519c1874.
