### ISSUE TITLE
Support stacks filling

### ISSUE THREAD

**Issue by Nordsoft91** [peter-kish/gloot#209]
There is prototype
```json
{
  "id": "my_item",
  "max_stack_size": 5
},
```

There are 2 items of same id "my_item" in one InventoryStacked
```json
$InventoryItem1
{
  "id": "my_item",
  "max_stack_size": 5,
  "stack_size": 4
},

$InventoryItem2
{
  "id": "my_item",
  "max_stack_size": 5,
  "stack_size": 2
},
```

I want to have a method to do auto split-merge (InventoryItem2 -> InventoryItem1):
```json
$InventoryItem1
{
  "id": "my_item",
  "max_stack_size": 5,
  "stack_size": 5
},

$InventoryItem2
{
  "id": "my_item",
  "max_stack_size": 5,
  "stack_size": 1
},
```

**Comment by peter-kish** [comment]
`pack(item)` has been added to [`InventoryStacked`](https://github.com/peter-kish/gloot/blob/master/docs/inventory_stacked.md) and [`InventoryGridStacked`](https://github.com/peter-kish/gloot/blob/master/docs/inventory_grid_stacked.md) in [v2.4.9](https://github.com/peter-kish/gloot/releases/tag/v2.4.9). It can be used to merge the given item stack with all compatible items in the same inventory.
