### ISSUE TITLE
Bug: Trying to stack stackable item from inventoryGrid to InventoryGridStacked causes a crash.

### ISSUE THREAD

**Issue by LeeWannacott** [peter-kish/gloot#225]
use case: a shop might have InventoryGrid with nothing stackable because then you could literally stack and then transfer and get two for the price of one. but players inventory is stackable (although I guess could program; price * the stack size). Either way I don't know if it should crash the game. I'll probably switch my shops to inventoryGridStacked anyway :thinking: I report it anyhow. 

![image](https://github.com/user-attachments/assets/2e8fba01-bc83-4cf9-8dad-ce5ac4e28f58)

Note: In Godot editor right click "Change Type" from inventoryGrid -> inventoryGridStacked doesn't seem to work, so I'll probably have to delete and recreate.

**Comment by peter-kish** [comment]
eb48df094258a9affd29b34fc979ac221985629f will probably fix this, but I think I should also add some more tests for moving items between inventories of different types at some point.
