### ISSUE TITLE
Issues with Slot

### ISSUE THREAD

**Issue by Flavore669** [peter-kish/gloot#237]
I keep on getting this error when I'm trying to run the main scene.
![issue](https://github.com/user-attachments/assets/616d3d2f-6d9d-4e59-a406-a3f0e189c2e9)

I don't really know what went wrong, but prior to the issues I was trying to instantiate a ItemRefSlot node and then this issue occurred even when I detached the script. When I deleted and reinstalled gloot it seemingly runs like normal in the editor, but I still get the same error, and then it stops running in the editor shortly after. Lastly the examples seem to run fine so I'm unsure if it's a bug or if I'm doing something wrong.

**Comment by peter-kish** [comment]
Hmm... it's difficult to diagnose this with only the error message. Do you have some example scene that demonstrates the issue?

**Comment by Flavore669** [comment]
Sorry, I'll try being more specific. The error appears when the CtrlItemSlot is connected to an ItemSlotRef, it seems to function fine with a regular item slot but for some reason the ItemSlotRef is bugged and doesn't work in any other scene.
![image](https://github.com/user-attachments/assets/9209ba65-4a1a-4779-924a-9d5a1f1e8cd5)

I do have this project in a private repository of my own, I'm really new to GitHub but is it a good idea if I just share it with you and you can just debug the project directly?

**Comment by peter-kish** [comment]
I think I figured it out, it was a bug on my side. Luckily the fix seems simple... It should be fixed in 7ccd8bbcafae90098efafb3b1bafdce2b9b420c9.

**Comment by Flavore669** [comment]
It's working on my end now! Thank you so much!
