### ISSUE TITLE
Bug: Drag preview keeps shape when item dragged outside of the InventoryGrid

### ISSUE THREAD

**Issue by LeeWannacott** [peter-kish/gloot#241]
If you drag item outside of inventory grid it keeps the shape of the item instead of resetting to a single square like when you dragged the item to a another place in the grid.

Note: This is a separate issue to the other issue; I double checked.

https://github.com/user-attachments/assets/cc3a5c1f-fec9-4c70-a979-252cac94bf91

Issue also happens if dropping on a different inventory item that is a different shape i.e (items that can't swap).

**Comment by peter-kish** [comment]
You're right. It should be fixed now: f3449a2b31de485cfd3f6c9a800245e6fe6d01f3

**Comment by LeeWannacott** [comment]
> `You're right. It should be fixed now: https://github.com/peter-kish/gloot/commit/f3449a2b31de485cfd3f6c9a800245e6fe6d01f3`

Looks fixed to me! thanks.
