### ISSUE TITLE
How to rotate the holding item?

### ISSUE THREAD

**Issue by Visnicio** [peter-kish/gloot#249]
I'm using a StackGrid type inventory but I dont seem to find any method that can return me the holding item so I can pass it to `rotate_item`

Theres only the `get_selected_inventory_item` in the control node but it does not return the holding item

**Comment by Visnicio** [comment]
![image](https://github.com/user-attachments/assets/f53261fb-4af9-4095-9e94-1d62ca8f688a)

**Comment by peter-kish** [comment]
Hi! Can you clarify what you mean by "holding item"? Is that item equipped in an item slot?

**Comment by Visnicio** [comment]
sorry for the confusion, by "holding item" I mean the item that the player is currently dragging, I would like to be able to rotate the item while I'm dragging it in the inventory

**Comment by peter-kish** [comment]
Yeah, that is sadly not implemented in the current version. I will look into implementing something like `CtrlInventoryGrid.get_grabbed_inventory_item()` or similar. Then it will be just a matter of calling `InventoryGrid.rotate_item(item)` on it.

**Comment by Visnicio** [comment]
Nice, gonna wait patiently for the next update then :)
