### ISSUE TITLE
[Bug] - `ItemSlot` "image" property does not scale to fit Inspector 

### ISSUE THREAD

**Issue by Thiago-Morais** [peter-kish/gloot#255]
Any ItemSlot node displaying an item with an "image" uses the full-size image

That means the image takes too much space and sometimes stays out of bounds

<img src="https://github.com/user-attachments/assets/5d5c3f82-394e-4652-9501-8c11d3f8abbf" width=70%>

> _An `ItemSlot` node with a 512x512 image taking too much space in the inspector_
<br>
<img src="https://github.com/user-attachments/assets/8bfdf181-4525-404f-a022-a00d669623f0" width=30%>

> _An `ItemSlot` node with a 512x512 image covering other properties in a narrow inspector_
<br>
The ItemRefSlot node overrides the minimum inspector width to fit the biggest image width

<img src="https://github.com/user-attachments/assets/816be5cf-388a-4ad1-8b9d-0196d06375e6" width=70%>

> _An `ItemRefSlot` that changed the inspector width to fit the biggest image_
<br>
<img src="https://github.com/user-attachments/assets/c8492240-8a14-4bcb-95dc-62758f106289" width=70%>

> _An `ItemRefSlot`'s `Equipped Item` dropdown using full-size images_

**Comment by peter-kish** [comment]
Should be fixed in 5f44973bc8d08ea12f5cba53548285c26268c828 and ad49e86245e3c3c65eb808d32afc2778cfdb9e54.
