### ISSUE TITLE
Adding items to inventories from code

### ISSUE THREAD

**Issue by tupcakes** [peter-kish/gloot#33]
ok I've been banging my head against this for the past half week. I'm having a heck of a time getting items to add to my inventory. Also, if you don't want these kind of question in the issues feel free to just close it. I'll completely understand.

I have a [basic scene](https://i.imgur.com/COX8ZG3.png) for my inventory with a CtrlInventoryGrid as a child node. I'm creating the InventoryGrid in code (see below). I'm fairly certain the InventoryGrid node is getting created and linked to the CtrlInventoryGrid via the inventory_path property. However when I try to find a free place for the item or add an item I get an error that says:

> Invalid call. Nonexistent function 'get_property' in base 'NiL'.

Additionally, ``` inventory_grid_node.get_item_by_id("laptop")``` seems to be null so it's acting like it's not even finding the item in the protoset.

```json
[
    {
        "id": "laptop",
        "width": 2,
        "height": 2,
        "name": "Laptop",
        "description": "A general purpose laptop for business.",
        "image": "res://items/assets/laptop.png"
    }
]
```
 
I see that get_property is a method of InventoryItem. is the get_item_by_id function I'm trying to call just searching for the item id in the exiting inventory? also if thats the case, how does one add an item to an inventory in code?

```GDScript
func _ready():
	var inventory_grid = initialize_inventory_grid()
	create_inventory_grid(inventory_grid)
	assign_inventory_grid_to_panel(inventory_grid)

        var inventory_grid_node = get_node("InventoryGrid")
	
	add_item(inventory_grid_node)
	

func initialize_inventory_grid() -> InventoryGrid:
	var inventory_grid = load("res://addons/gloot/inventory_grid.gd").new()
	inventory_grid.size = Vector2(4, 5)
	inventory_grid.item_protoset = load("res://items/ItemProtoset.tres")
	inventory_grid.name = "InventoryGrid"
	return inventory_grid

func create_inventory_grid(inventory_grid):
	add_child(inventory_grid)

func assign_inventory_grid_to_panel(inventory_grid: InventoryGrid):
	var inventory_panel = get_node("CtrlInventoryGrid")
	inventory_panel.inventory_path = inventory_grid.get_path()

func add_item(inventory_grid_node):
	var item = inventory_grid_node.get_item_by_id("laptop")
	var item_position = inventory_grid_node.find_free_place(item)
	inventory_grid_node.add_item_at(item, item_position)

```

**Comment by filipinyo** [comment]
I think get_item_by_id is taking stuff from the current inventory item list and not from the protoset. I'm currently facing the same issue.

**Comment by tupcakes** [comment]
> I think get_item_by_id is taking stuff from the current inventory item list and not from the protoset. I'm currently facing the same issue. There should be a function implemented, that creates items based on the id from the protoset.

Thats what I'm also thinking based on what I'm seeing. I originally thought get_item_by_id would automatically search the protoset attached to the inventory. So either thats not how it work, or my code isn't actually attaching the protoset to the item_protoset property.

**Comment by filipinyo** [comment]
@tupcakes 

I've modified inventory.gd script and added this function

`
func create_and_add_item(id: String) -> InventoryItem:	
	var items = parse_json(item_protoset.json_data)
	var item_to_create = null
	for item in items:        
		if item.id == id:
			item_to_create = item
			break

	assert(item_to_create != null, "Item with ID not found")		
	var item = InventoryItem.new()
	item.deserialize(item_to_create)
	self.add_item(item)
	return item
`

You call this on any inventory and the item should be created and added. It also returns the created item if you'd need it etc. Hope it helps.

**Comment by peter-kish** [comment]
Hey, thanks for the input!

>is the get_item_by_id function I'm trying to call just searching for the item id in the exiting inventory? also if thats the case, how does one add an item to an inventory in code?

Yes, `get_item_by_id` searches through the items that are already in the inventory. It is not used to create an `InventoryItem` based on the given prototype ID. The current way of adding items in code would be the following:
```
var item = InventoryItem.new()
item.prototype_id = "laptop"
inventory_grid_node.add_item(item)
```
(`find_free_place` is not really necessary, as `InventoryGrid.addItem()` already looks for a free place)

It's not very intuitive, especially since it is not mentioned anywhere in the docs, but that's because I was mostly focusing on inventory manipulation using the editor and the GDScript API is still a bit lacking.

However, I still think adding items from code should be straight forward and there should definitely be a helper method (similar to what @filipinyo suggested) that does that in one line.

I will rename this issue to be more descriptive, but I will keep it open until something like that is implemented (shouldn't take long).

**Comment by tupcakes** [comment]
Thank you both!

```GDSCript
item.prototype_id = "laptop"
````

above, is what I was missing. I'd tried so many things. It seems so simple now.
