### ISSUE TITLE
Having trouble displaying an item's image in Controls, but they work fine inside the Inspector plugin

### ISSUE THREAD

**Issue by Polatrite** [peter-kish/gloot#4]
I followed the steps to setup the plugin (recapping here):

1. Created an `ItemProtoset`, JSON below:
```json
[
	{
		"id": "Fireball",
		"name": "Fireball",
		"image": "res://assets/items/health-potion.png"
	},
	{
		"id": "Pyroblast",
		"name": "Pyroblast",
		"image": "res://assets/items/health-potion.png"
	},
	{
		"id": "Meteor",
		"name": "Meteor",
		"image": "res://assets/items/health-potion.png"
	},
	{
		"id": "Flame Horizon",
		"name": "Flame Horizon",
		"image": "res://assets/items/health-potion.png"
	},
	{
		"id": "Rising Flames",
		"name": "Rising Flames",
		"image": "res://assets/items/health-potion.png"
	}
]
```
2. Created both an `InventoryGrid` and `InventoryStacked` node in my debug scene.
3. Assigned the above `ItemProtoset` to these nodes and configured the width/height and capacity respectively
4. Added individual items to the inventory

![image](https://user-images.githubusercontent.com/1864992/175786169-b121e42c-9593-4ac5-ab85-4c4fce249d5e.png)

5. Created both a `CtrlInventoryGrid` and `CtrlInventoryStacked`, pointing at their respective Inventory nodes
6. Made sure these are positioned well and visible within the scene
7. Set the `default_item_texture/icon` properties in each

![image](https://user-images.githubusercontent.com/1864992/175786221-f6d52eeb-ddfd-4a41-ada2-e0757b4195aa.png)

8. Launch the project

![image](https://user-images.githubusercontent.com/1864992/175786284-39920732-0e8e-4e25-9547-438710b34eee.png)

**Expected results:**

The few items configured in each Inventory would display inside the controls.

**Actual results:**

The controls display fine, but have no items within them.

**Version stuff:**

Latest master `d71a32358`, Godot v3.5.beta4.official, GDscript binary (no mono), Windows 10

**Comment by peter-kish** [comment]
Seems like commit 37ebef088c8ba6ac36d6632f52880350ae1315ae broke something. Working on it.
