### ISSUE TITLE
update_json_data nonexistent

### ISSUE THREAD

**Issue by HiThere54** [peter-kish/gloot#66]
When closing the ProtoSet editor, Godot throws
 res://addons/gloot/editor/edit_protoset_button.gd:42 - Invalid call. Nonexistent function 'update_json_data' in base 'Resource (item_protoset.gd)'.

**Comment by peter-kish** [comment]
Hey, thanks for the input. I player around with it a little, but could not reproduce the issue.

Can you give some details about your setup and the circumstances?
