### ISSUE TITLE
`InventoryGridEx` bad performance when mouse moves

### ISSUE THREAD

**Issue by mxnemu** [peter-kish/gloot#68]
1. create a `InventoryGridEx` with a 20x40 or bigger inventory
2. start the game
3. move the mouse around a bit and see the framerate drop

tested in in godot 3.5.1

The problem seems to be in `_input`.

Running in a for loop over every cell to check a ton of properties and if the mouse is in each field seems to be connected to it, but I haven't read the code in detail. This is not a problem in the non-ex version of InventoryGrid

![profiler](https://user-images.githubusercontent.com/560561/203136634-ec7c7567-b04e-40dd-9389-fe0061776c56.png)

**Comment by peter-kish** [comment]
Fixed in https://github.com/peter-kish/gloot/pull/72.
More optimizations are certainly possible, but this should fix the worst slowdowns.
