### ISSUE TITLE
Add the ability to add items to a grid without setting a position

### ISSUE THREAD

**Issue by ghostfreeman** [peter-kish/gloot#76]
I think your docs outline this somewhere indicating you're working on this, but this would be very helpful in managing the inventory without having to fire a sort after an addition.

**Comment by peter-kish** [comment]
Not use what you mean by "having to fire a sort after an addition", but you can add items to an `InventoryGrid` using `add_item(item)` and it will try to find a free place for it on the grid.

There is this "auto sorting" feature though, which tries to detect overlapping items whenever a new one is added and calls a `sort()` automatically. However, I'm thinking about removing that and just returning `false` if there's no free space for the item or it can't be placed at the given coordinates.
