### ISSUE TITLE
Stack size support for `inventoryGrid` (Minecraft style)

### ISSUE THREAD

**Issue by peter-kish** [peter-kish/gloot#78]
In some games that use a grid based inventory system it would be useful to have the support for item stacks, similar to Minecraft.
This would require storing the current stack size for a given item, as well as the maximal stack size.

**Comment by zortordor** [comment]
Is this feature on the way?

**Comment by peter-kish** [comment]
Development has been kinda slow lately due to personal obligations, but I did experiment with implementing this feature by making `InventoryGrid` inherit `InventoryStacked` (not sure if I'm going to commit to this approach though, as it seems to increase the complexity of `InventoryGrid` quite a bit).
It is one of the higher priority features I intend to implement as such inventories are often used. Hope I'll find some time to work on it soon.

**Comment by zortordor** [comment]
Oh, okay, thanks

**Comment by peter-kish** [comment]
`InventoryGridStacked` is added in https://github.com/peter-kish/gloot/pull/99
It extends `InventoryGrid` and implements some logic for managing item stacks in a grid based inventory (check out the [documentation](https://github.com/peter-kish/gloot/blob/master/docs/inventory_grid_stacked.md) for more details).
