### ISSUE TITLE
Crash during some drag and drop interactions

### ISSUE THREAD

**Issue by LunaBold** [peter-kish/gloot#86]
While creating a self-refilling container to allow dragging into other inventorys, i encountered a crash involving line 389 of ctrl_inventory_grid.gd.

A possible solution that has been working for me is to put this code before it:

```
if typeof(source_inventory) == TYPE_NIL:
		return
```

I was not sure what was causing the crash, but it seems to involve dragging a item that stopped existing in my code that deleted items that were dragged out of the inventory.

**Comment by peter-kish** [comment]
Haven't seen a crash like that before. Maybe some additional information about your setup could help (not sure what a self-refilling container is).

**Comment by LunaBold** [comment]
i'll see if i can try to recreate it and then link a scene to download, will get back with it asap but probably not today
