### ISSUE TITLE
Crash with get_item_position

### ISSUE THREAD

**Issue by LunaBold** [peter-kish/gloot#87]
line 33 of inventory_grid.gd causes a crash while dragging an item from an inventory to another, when the first inventory is completely full, but the item was not dropped in a free space on the second inventory. commenting out this line fixes the issue.

**Comment by peter-kish** [comment]
I gave this a try real quick but couldn't reproduce the issue. I used the `inventory_grid_transfer.tscn` example scene where I filled the left inventory with items before running the scene. I couldn't get any crashes to happen when dragging items over to the right, neither on occupied or unoccupied spaces.
Do you have any additional info about your setup that could help reproduce the crash (or even better and simple scene that demonstrates it)?
