### ISSUE TITLE
create_and_add_item() only creates and adds the first prototype in the protoset

### ISSUE THREAD

**Issue by zortordor** [peter-kish/gloot#93]
The title says it all basically. I assume the protoset is working correctly, since whenever i add items in the inspector it works just fine and i can also get any property of any item with get_property(). I'm probably doing something wrong, i just can't figure out what it is.

**Comment by peter-kish** [comment]
Yup, there was a bug. Luckily it was an easy fix.
`create_and_add_item()` should be working properly now.

**Comment by zortordor** [comment]
Thanks!

**Comment by zortordor** [comment]
Quick question if i may: how do i make the item icon bigger?
