### ISSUE TITLE
add_item_automerge should not add if has custom properties

### ISSUE THREAD

**Issue by andersmmg** [peter-kish/gloot#94]
I'd expect that using add_item_automerge would only add to matching items, not ones with extra properties defined. Like say I have a unique version of an item you could get, if I get another normal version of that item, it shouldn't add to the unique item which it currently does unless I'm using it incorrectly somehow.

**Comment by peter-kish** [comment]
Yeah, that makes sense. I didn't really consider merging item properties when I implemented `add_item_automerge`.
I will probably add a check to see if item properties are compatible before merging.

**Comment by peter-kish** [comment]
Should be fixed in 7ae35637cfac1cfac2988649058b05694b653a63
