### ISSUE TITLE
create_and_add_item() still seems to be only adding the first prototype

### ISSUE THREAD

**Issue by tupcakes** [peter-kish/gloot#96]
Yup, there was a bug. Luckily it was an easy fix.
`create_and_add_item()` should be working properly now.

_Originally posted by @peter-kish in https://github.com/peter-kish/gloot/issues/93#issuecomment-1493257359_

I think this issue is still happening. I've tried several different methods to create the items, but the issue persists. get_prototype() does return the correct protoset however.

plugin.cfg
```
name="GLoot"
description="A universal inventory system for the Godot game engine"
author="Peter Kish"
version="2.2.0"
script="gloot.gd"
```

protoset
```
[
  {
    "id": "wheat",
    "name": "Wheat",
    "stack_size": "1",
    "weight": 1
  },
  {
    "id": "iron",
    "name": "Iron",
    "stack_size": "1",
    "weight": 10
  },
  {
    "id": "wood",
    "name": "Wood",
    "stack_size": "1",
    "weight": 5
  },
  {
    "id": "bread",
    "name": "Bread",
    "stack_size": "1",
    "weight": 2
  }
]
```

code for testing
```
var protoset = preload("res://gloot_inventory/items_protoset.tres")

func _ready():
	PlayerManager.player = self
	Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
	
	
	#### testing
	var item = InventoryItem.new()
	item.prototype_id = "wheat"
	inventory_stacked.add_item_automerge(item) # creates wheat
	item = InventoryItem.new()
	item.prototype_id = "bread"
	inventory_stacked.add_item(item) # does not create bread
	inventory_stacked.create_and_add_item("bread") # does not create bread
	
	print(inventory_stacked.create_and_add_item("bread").get_title()) # does not create bread, returns wheat
	print(protoset.get_prototype("bread")) # outputs the correct prototype for bread
	#### testing
```

**Comment by tupcakes** [comment]
I had some time to look into it a little more I think I see the issue. I downloaded the version from the asset library. However despite being 2.2.0 like is on github the code doesn't reflect the change made last month for some reason.

the version from the asset library
```
func create_and_add_item(prototype_id: String) -> InventoryItem:
    var item: InventoryItem = InventoryItem.new()
    item.prototype_id = prototype_id
    if add_item(item):
        return item
    else:
        item.free()
        return null
```

github
```
func create_and_add_item(prototype_id: String) -> InventoryItem:
	var item: InventoryItem = InventoryItem.new()
	item.protoset = item_protoset
	item.prototype_id = prototype_id
	if add_item(item):
		return item
	else:
		item.free()
		return null
```

as soon as I updated the function it started working.

**Comment by peter-kish** [comment]
Yeah sorry, the version on the asset library doesn't contain the latest changes, just the latest release - and I'm only creating releases once there are enough changes (otherwise I'd have to update the version on the asset library after each PR).

**Comment by tupcakes** [comment]
Looks like add_item() might still have something wrong with it after making that change.

**Comment by tupcakes** [comment]
> Yeah sorry, the version on the asset library doesn't contain the latest changes, just the latest release - and I'm only creating releases once there are enough changes (otherwise I'd have to update the version on the asset library after each PR).

makes sense. I have no idea how the asset library stuff is pulled so I wasn't sure what was up there.

**Comment by tupcakes** [comment]
> Looks like add_item() might still have something wrong with it after making that change.

I'm a derp. helps if I assign the protoset when creating an items. :)
```
var item = InventoryItem.new()
item.protoset = protoset
item.prototype_id = "wheat"
inventory_stacked.add_item_automerge(item) # creates wheat
```
